
export type Student = {
  firstName: string;
  lastName: string;
  email: string;
  age: number;
  grade: string;
};

export const initialData: Student[] = [
  {
    firstName: "John",
    lastName: "Doe",
    email: "john.doe@example.com",
    age: 14,
    grade: "8th",
  },
  {
    firstName: "Jane",
    lastName: "Smith",
    email: "jane.smith@example.com",
    age: 15,
    grade: "9th",
  },
  {
    firstName: "Michael",
    lastName: "Johnson",
    email: "michael.johnson@example.com",
    age: 13,
    grade: "7th",
  },
  {
    firstName: "Emily",
    lastName: "Davis",
    email: "emily.davis@example.com",
    age: 12,
    grade: "6th",
  },
  {
    firstName: "David",
    lastName: "Brown",
    email: "david.brown@example.com",
    age: 16,
    grade: "10th",
  },
  {
    firstName: "William",
    lastName: "Miller",
    email: "william.miller@example.com",
    age: 14,
    grade: "8th",
  },
  {
    firstName: "Olivia",
    lastName: "Wilson",
    email: "olivia.wilson@example.com",
    age: 15,
    grade: "9th",
  },
  {
    firstName: "Liam",
    lastName: "Moore",
    email: "liam.moore@example.com",
    age: 13,
    grade: "7th",
  },
  {
    firstName: "Sophia",
    lastName: "Taylor",
    email: "sophia.taylor@example.com",
    age: 12,
    grade: "6th",
  },
  {
    firstName: "James",
    lastName: "Anderson",
    email: "james.anderson@example.com",
    age: 16,
    grade: "10th",
  },
  {
    firstName: "Isabella",
    lastName: "Thomas",
    email: "isabella.thomas@example.com",
    age: 14,
    grade: "8th",
  },
  {
    firstName: "Alexander",
    lastName: "Jackson",
    email: "alexander.jackson@example.com",
    age: 15,
    grade: "9th",
  },
  {
    firstName: "Mia",
    lastName: "White",
    email: "mia.white@example.com",
    age: 13,
    grade: "7th",
  },
  {
    firstName: "Ethan",
    lastName: "Harris",
    email: "ethan.harris@example.com",
    age: 14,
    grade: "8th",
  },
  {
    firstName: "Ava",
    lastName: "Clark",
    email: "ava.clark@example.com",
    age: 15,
    grade: "9th",
  },
  {
    firstName: "Noah",
    lastName: "Lewis",
    email: "noah.lewis@example.com",
    age: 13,
    grade: "7th",
  },
  {
    firstName: "Charlotte",
    lastName: "Walker",
    email: "charlotte.walker@example.com",
    age: 12,
    grade: "6th",
  },
  {
    firstName: "Benjamin",
    lastName: "Hall",
    email: "benjamin.hall@example.com",
    age: 16,
    grade: "10th",
  },
  {
    firstName: "Amelia",
    lastName: "Young",
    email: "amelia.young@example.com",
    age: 14,
    grade: "8th",
  },
  {
    firstName: "Lucas",
    lastName: "Allen",
    email: "lucas.allen@example.com",
    age: 15,
    grade: "9th",
  },
  {
    firstName: "Mason",
    lastName: "King",
    email: "mason.king@example.com",
    age: 13,
    grade: "7th",
  },
  {
    firstName: "Harper",
    lastName: "Wright",
    email: "harper.wright@example.com",
    age: 12,
    grade: "6th",
  },
  {
    firstName: "Henry",
    lastName: "Scott",
    email: "henry.scott@example.com",
    age: 16,
    grade: "10th",
  },
  {
    firstName: "Lily",
    lastName: "Adams",
    email: "lily.adams@example.com",
    age: 14,
    grade: "8th",
  },
  {
    firstName: "Sam",
    lastName: "Baker",
    email: "sam.baker@example.com",
    age: 15,
    grade: "9th",
  },
  {
    firstName: "Ella",
    lastName: "Carter",
    email: "ella.carter@example.com",
    age: 13,
    grade: "7th",
  },
  {
    firstName: "Jack",
    lastName: "Dixon",
    email: "jack.dixon@example.com",
    age: 12,
    grade: "6th",
  },
  {
    firstName: "Grace",
    lastName: "Evans",
    email: "grace.evans@example.com",
    age: 16,
    grade: "10th",
  },
  {
    firstName: "Leo",
    lastName: "Foster",
    email: "leo.foster@example.com",
    age: 14,
    grade: "8th",
  },
  {
    firstName: "Zoe",
    lastName: "Green",
    email: "zoe.green@example.com",
    age: 15,
    grade: "9th",
  },
  {
    firstName: "Owen",
    lastName: "Hill",
    email: "owen.hill@example.com",
    age: 13,
    grade: "7th",
  },
  {
    firstName: "Emma",
    lastName: "Iverson",
    email: "emma.iverson@example.com",
    age: 12,
    grade: "6th",
  },
  {
    firstName: "Ryan",
    lastName: "Jenkins",
    email: "ryan.jenkins@example.com",
    age: 16,
    grade: "10th",
  },
  {
    firstName: "Hannah",
    lastName: "Keller",
    email: "hannah.keller@example.com",
    age: 14,
    grade: "8th",
  },
  {
    firstName: "Eli",
    lastName: "Long",
    email: "eli.long@example.com",
    age: 15,
    grade: "9th",
  },
  {
    firstName: "Avery",
    lastName: "Mitchell",
    email: "avery.mitchell@example.com",
    age: 13,
    grade: "7th",
  },
  {
    firstName: "Isaac",
    lastName: "Nelson",
    email: "isaac.nelson@example.com",
    age: 14,
    grade: "8th",
  },
  {
    firstName: "Nora",
    lastName: "Ortiz",
    email: "nora.ortiz@example.com",
    age: 15,
    grade: "9th",
  },
  {
    firstName: "Caleb",
    lastName: "Perez",
    email: "caleb.perez@example.com",
    age: 13,
    grade: "7th",
  },
  {
    firstName: "Sophie",
    lastName: "Quinn",
    email: "sophie.quinn@example.com",
    age: 12,
    grade: "6th",
  },
  {
    firstName: "Nathan",
    lastName: "Reed",
    email: "nathan.reed@example.com",
    age: 16,
    grade: "10th",
  },
  {
    firstName: "Luna",
    lastName: "Simmons",
    email: "luna.simmons@example.com",
    age: 14,
    grade: "8th",
  },
  {
    firstName: "Aiden",
    lastName: "Turner",
    email: "aiden.turner@example.com",
    age: 15,
    grade: "9th",
  }
];